### ISSUE TITLE
SNMP get is not initializing the messageDispatcher factory

### ISSUE THREAD

**Issue by niau** [iTransformers/snmp2xml4j#1]
` public Get(String oid, CommunityTarget target,TransportMappingAbstractFactory transportFactory, MessageDispatcherAbstractFactory messageDispatcherAbstractFactory){
        this.oid = oid;

```
    this.target = target;
    this.transportFactory = transportFactory;
    this.messageDispatcherFactory = messageDispatcherFactory;
    this.transportFactory = transportFactory;
    localAddress = new UdpAddress("0.0.0.0/0");

}`
```

Should be this.messageDispatcherFactory=messageDispatcherAbstractFactory

**Comment by vasil-yordanov** [comment]
Correct this is a bug.

On Mon, Feb 29, 2016 at 9:45 AM, Nikolay Milovanov <notifications@github.com
